export default [
  {
    id: "TFT_Portals_Augments_GoldFirst",
    name: "黄金前奏",
    desc: "这局游戏供应的第一个强化符文将是黄金阶。",
    logo: "https://game.gtimg.cn/images/lol/act/img/tft/RegionPortal/TFT_Portals_Augments_GoldFirst.png",
    video: "",
    bgImage: "",
    country: "黄金前奏",
    versionId: "133",
    seasonId: "45",
    creater: "v_qjmqu",
    createTime: "2024-03-11 10:48:27",
    updater: "",
    updateTime: "",
    isDelete: "0",
  },
  {
    id: "TFT_Portals_Augments_PrismaticFirst",
    name: "棱彩前奏",
    desc: "这局游戏供应的第一个强化符文将是棱彩阶。",
    logo: "https://game.gtimg.cn/images/lol/act/img/tft/RegionPortal/TFT_Portals_Augments_PrismaticFirst.png",
    video: "",
    bgImage: "",
    country: "棱彩前奏",
    versionId: "133",
    seasonId: "45",
    creater: "v_qjmqu",
    createTime: "2024-03-11 10:48:27",
    updater: "",
    updateTime: "",
    isDelete: "0",
  },
  {
    id: "TFT_Portals_Augments_TripleGold",
    name: "三金交响曲",
    desc: "这局游戏供应的所有强化符文都将是黄金阶。",
    logo: "https://game.gtimg.cn/images/lol/act/img/tft/RegionPortal/TFT_Portals_Augments_TripleGold.png",
    video: "",
    bgImage: "",
    country: "三金交响曲",
    versionId: "133",
    seasonId: "45",
    creater: "v_qjmqu",
    createTime: "2024-03-11 10:48:27",
    updater: "",
    updateTime: "",
    isDelete: "0",
  },
  {
    id: "TFT_Portals_Augments_TriplePrismatic",
    name: "三彩交响曲",
    desc: "这局游戏提供的所有强化符文都将是棱彩阶。",
    logo: "https://game.gtimg.cn/images/lol/act/img/tft/RegionPortal/TFT_Portals_Augments_TriplePrismatic.png",
    video: "",
    bgImage: "",
    country: "三彩交响曲",
    versionId: "133",
    seasonId: "45",
    creater: "v_qjmqu",
    createTime: "2024-03-11 10:48:27",
    updater: "",
    updateTime: "",
    isDelete: "0",
  },
  {
    id: "TFT_Portals_Augments_PrismaticThird",
    name: "棱彩终章",
    desc: "这局游戏供应的最后一个强化符文将是棱彩阶。",
    logo: "https://game.gtimg.cn/images/lol/act/img/tft/RegionPortal/TFT_Portals_Augments_PrismaticThird.png",
    video: "",
    bgImage: "",
    country: "棱彩终章",
    versionId: "133",
    seasonId: "45",
    creater: "v_qjmqu",
    createTime: "2024-03-11 10:48:27",
    updater: "",
    updateTime: "",
    isDelete: "0",
  },
  {
    id: "TFT_Portals_Augments_GoldThird",
    name: "黄金终章",
    desc: "这局游戏供应的最后一个强化符文将是黄金阶。",
    logo: "https://game.gtimg.cn/images/lol/act/img/tft/RegionPortal/TFT_Portals_Augments_GoldThird.png",
    video: "",
    bgImage: "",
    country: "黄金终章",
    versionId: "133",
    seasonId: "45",
    creater: "v_qjmqu",
    createTime: "2024-03-11 10:48:27",
    updater: "",
    updateTime: "",
    isDelete: "0",
  },
  {
    id: "TFT_Portals_Champions_ChampionStart",
    name: "3费弈子",
    desc: "开局拥有1个随机的3费弈子。",
    logo: "https://game.gtimg.cn/images/lol/act/img/tft/RegionPortal/TFT_Portals_Champions_ChampionStart.png",
    video: "",
    bgImage: "",
    country: "3费弈子",
    versionId: "133",
    seasonId: "45",
    creater: "v_qjmqu",
    createTime: "2024-03-11 10:48:27",
    updater: "",
    updateTime: "",
    isDelete: "0",
  },
  {
    id: "TFT_Portals_Champions_UpgradedChampions",
    name: "2星开局",
    desc: "开局拥有1个2星1费弈子。",
    logo: "https://game.gtimg.cn/images/lol/act/img/tft/RegionPortal/TFT_Portals_Champions_UpgradedChampions.png",
    video: "",
    bgImage: "",
    country: "2星开局",
    versionId: "133",
    seasonId: "45",
    creater: "v_qjmqu",
    createTime: "2024-03-11 10:48:27",
    updater: "",
    updateTime: "",
    isDelete: "0",
  },
  {
    id: "TFT_Portals_Champions_DuplicatorStart",
    name: "英雄复制器",
    desc: "使用英雄复制器开始游戏。",
    logo: "https://game.gtimg.cn/images/lol/act/img/tft/RegionPortal/TFT_Portals_Champions_DuplicatorStart.png",
    video: "",
    bgImage: "",
    country: "英雄复制器",
    versionId: "133",
    seasonId: "45",
    creater: "v_qjmqu",
    createTime: "2024-03-11 10:48:27",
    updater: "",
    updateTime: "",
    isDelete: "0",
  },
  {
    id: "TFT_Portals_Champions_TripleStart",
    name: "3弈子",
    desc: "开局拥有3个随机的1费弈子。",
    logo: "https://game.gtimg.cn/images/lol/act/img/tft/RegionPortal/TFT_Portals_Champions_TripleStart.png",
    video: "",
    bgImage: "",
    country: "3弈子",
    versionId: "133",
    seasonId: "45",
    creater: "v_qjmqu",
    createTime: "2024-03-11 10:48:27",
    updater: "",
    updateTime: "",
    isDelete: "0",
  },
  {
    id: "TFT_Portals_Gold_GoldPerAugment",
    name: "强化符文赠金",
    desc: "你每次选择一个强化符文时，会获得3x你已有强化符文数的金币。",
    logo: "https://game.gtimg.cn/images/lol/act/img/tft/RegionPortal/TFT_Portals_Gold_GoldPerAugment.png",
    video: "",
    bgImage: "",
    country: "强化符文赠金",
    versionId: "133",
    seasonId: "45",
    creater: "v_qjmqu",
    createTime: "2024-03-11 10:48:27",
    updater: "",
    updateTime: "",
    isDelete: "0",
  },
  {
    id: "TFT_Portals_Gold_GoldPerItem",
    name: "装备赠金",
    desc: "每当你合出一件成装时，获得2金币。",
    logo: "https://game.gtimg.cn/images/lol/act/img/tft/RegionPortal/TFT_Portals_Gold_GoldPerItem.png",
    video: "",
    bgImage: "",
    country: "装备赠金",
    versionId: "133",
    seasonId: "45",
    creater: "v_qjmqu",
    createTime: "2024-03-11 10:48:27",
    updater: "",
    updateTime: "",
    isDelete: "0",
  },
  {
    id: "TFT_Portals_Gold_Cashout",
    name: "梦幻金罐",
    desc: "在第 6-1 阶段，所有活着的玩家瓜分 120 金子。",
    logo: "https://game.gtimg.cn/images/lol/act/img/tft/RegionPortal/TFT_Portals_Gold_Cashout.png",
    video: "",
    bgImage: "",
    country: "梦幻金罐",
    versionId: "133",
    seasonId: "45",
    creater: "v_qjmqu",
    createTime: "2024-03-11 10:48:27",
    updater: "",
    updateTime: "",
    isDelete: "0",
  },
  {
    id: "TFT_Portals_ArtifactAnvil",
    name: "神器锻造器",
    desc: "开局拥有1个【神器锻造器】",
    logo: "https://game.gtimg.cn/images/lol/act/img/tft/RegionPortal/TFT_Portals_ArtifactAnvil.png",
    video: "",
    bgImage: "",
    country: "神器锻造器",
    versionId: "133",
    seasonId: "45",
    creater: "v_qjmqu",
    createTime: "2024-03-11 10:48:27",
    updater: "",
    updateTime: "",
    isDelete: "0",
  },
  {
    id: "TFT_Portals_Items_ComponentAnvil",
    name: "基础装备锻造器",
    desc: "开局拥有2个【基础装备锻造器】",
    logo: "https://game.gtimg.cn/images/lol/act/img/tft/RegionPortal/TFT_Portals_Items_ComponentAnvil.png",
    video: "",
    bgImage: "",
    country: "基础装备锻造器",
    versionId: "133",
    seasonId: "45",
    creater: "v_qjmqu",
    createTime: "2024-03-11 10:48:27",
    updater: "",
    updateTime: "",
    isDelete: "0",
  },
  {
    id: "TFT_Portals_Items_CompletedAnvil",
    name: "成装锻造器",
    desc: "开局拥有1个【成装锻造器】",
    logo: "https://game.gtimg.cn/images/lol/act/img/tft/RegionPortal/TFT_Portals_Items_CompletedAnvil.png",
    video: "",
    bgImage: "",
    country: "成装锻造器",
    versionId: "133",
    seasonId: "45",
    creater: "v_qjmqu",
    createTime: "2024-03-11 10:48:27",
    updater: "",
    updateTime: "",
    isDelete: "0",
  },
  {
    id: "TFT_Portals_Unique_ScuttlePuddle",
    name: "迅捷蟹水潭",
    desc: "野怪都被替换为可以掉落额外战利品的迅捷蟹。",
    logo: "https://game.gtimg.cn/images/lol/act/img/tft/RegionPortal/TFT_Portals_Unique_ScuttlePuddle.png",
    video: "",
    bgImage: "",
    country: "迅捷蟹水潭",
    versionId: "133",
    seasonId: "45",
    creater: "v_qjmqu",
    createTime: "2024-03-11 10:48:27",
    updater: "",
    updateTime: "",
    isDelete: "0",
  },
  {
    id: "TFT_Portals_Unique_MaxHealthIncrease",
    name: "大大英雄",
    desc: "开局拥有115玩家生命值。",
    logo: "https://game.gtimg.cn/images/lol/act/img/tft/RegionPortal/TFT_Portals_Unique_MaxHealthIncrease.png",
    video: "",
    bgImage: "",
    country: "大大英雄",
    versionId: "133",
    seasonId: "45",
    creater: "v_qjmqu",
    createTime: "2024-03-11 10:48:27",
    updater: "",
    updateTime: "",
    isDelete: "0",
  },
  {
    id: "TFT_Portals_DoubleItemCarousel",
    name: "灌铅选秀",
    desc: "基础装备选秀的每个英雄会携带2件(而非1件)基础装备",
    logo: "https://game.gtimg.cn/images/lol/act/img/tft/RegionPortal/TFT_Portals_DoubleItemCarousel.png",
    video: "",
    bgImage: "",
    country: "灌铅选秀",
    versionId: "133",
    seasonId: "45",
    creater: "v_qjmqu",
    createTime: "2024-03-11 10:48:27",
    updater: "",
    updateTime: "",
    isDelete: "0",
  },
  {
    id: "TFT_Portals_Combat_TrainingDummy",
    name: "训练假人",
    desc: "开局拥有1个训练假人。",
    logo: "https://game.gtimg.cn/images/lol/act/img/tft/RegionPortal/TFT_Portals_Combat_TrainingDummy.png",
    video: "",
    bgImage: "",
    country: "训练假人",
    versionId: "133",
    seasonId: "45",
    creater: "v_qjmqu",
    createTime: "2024-03-11 10:48:27",
    updater: "",
    updateTime: "",
    isDelete: "0",
  },
  {
    id: "TFT_Portals_Combat_ZoomZone",
    name: "弈子增速器",
    desc: "你的弈子们获得10%攻击速度和额外移动速度。",
    logo: "https://game.gtimg.cn/images/lol/act/img/tft/RegionPortal/TFT_Portals_Combat_ZoomZone.png",
    video: "",
    bgImage: "",
    country: "弈子增速器",
    versionId: "133",
    seasonId: "45",
    creater: "v_qjmqu",
    createTime: "2024-03-11 10:48:27",
    updater: "",
    updateTime: "",
    isDelete: "0",
  },
  {
    id: "TFT_Portals_Headliner_Showtime",
    name: "好戏开场",
    desc: "你的商店会以比你当前等级高1级的几率来刷新【赛季之星】。",
    logo: "https://game.gtimg.cn/images/lol/act/img/tft/RegionPortal/TFT_Portals_Headliner_Showtime.png",
    video: "",
    bgImage: "",
    country: "好戏开场",
    versionId: "133",
    seasonId: "45",
    creater: "v_qjmqu",
    createTime: "2024-03-11 10:48:27",
    updater: "",
    updateTime: "",
    isDelete: "0",
  },
  {
    id: "TFT_Portals_Headliner_Superstar",
    name: "多才多艺",
    desc: "【赛季之星】额外给自身的另一个羁绊+1计数。",
    logo: "https://game.gtimg.cn/images/lol/act/img/tft/RegionPortal/TFT_Portals_Headliner_Superstar.png",
    video: "",
    bgImage: "",
    country: "多才多艺",
    versionId: "133",
    seasonId: "45",
    creater: "v_qjmqu",
    createTime: "2024-03-11 10:48:27",
    updater: "",
    updateTime: "",
    isDelete: "0",
  },
  {
    id: "TFT_Portals_Augments_SilverGoldPrismatic",
    name: "金银彩",
    desc: "你将总会以白银阶、黄金阶和炫彩阶的顺序获得强化符文。",
    logo: "https://game.gtimg.cn/images/lol/act/img/tft/RegionPortal/TFT_Portals_Augments_SilverGoldPrismatic.png",
    video: "",
    bgImage: "",
    country: "金银彩",
    versionId: "133",
    seasonId: "45",
    creater: "v_qjmqu",
    createTime: "2024-03-11 10:48:27",
    updater: "",
    updateTime: "",
    isDelete: "0",
  },
  {
    id: "TFT_Portals_Champions_RandomChampion",
    name: "免费弈子",
    desc: "每个阶段两次，获得一个高费弈子。游戏越后期，获得的弈子身价更高。",
    logo: "https://game.gtimg.cn/images/lol/act/img/tft/RegionPortal/TFT_Portals_Champions_RandomChampion.png",
    video: "",
    bgImage: "",
    country: "免费弈子",
    versionId: "133",
    seasonId: "45",
    creater: "v_qjmqu",
    createTime: "2024-03-11 10:48:27",
    updater: "",
    updateTime: "",
    isDelete: "0",
  },
  {
    id: "TFT_Portals_Combat_KillCounter",
    name: "击杀统计",
    desc: "所有弈子都会显示其击杀数。",
    logo: "https://game.gtimg.cn/images/lol/act/img/tft/RegionPortal/TFT_Portals_Combat_KillCounter.png",
    video: "",
    bgImage: "",
    country: "击杀统计",
    versionId: "133",
    seasonId: "45",
    creater: "v_qjmqu",
    createTime: "2024-03-11 10:48:27",
    updater: "",
    updateTime: "",
    isDelete: "0",
  },
  {
    id: "TFT_Portals_Combat_ZoomZone",
    name: "弈子增速器",
    desc: "你的弈子们获得10%攻击速度和额外移动速度。",
    logo: "https://game.gtimg.cn/images/lol/act/img/tft/RegionPortal/TFT_Portals_Combat_ZoomZone.png",
    video: "",
    bgImage: "",
    country: "弈子增速器",
    versionId: "133",
    seasonId: "45",
    creater: "v_qjmqu",
    createTime: "2024-03-11 10:48:27",
    updater: "",
    updateTime: "",
    isDelete: "0",
  },
  {
    id: "TFT_Portals_Gold_MaxInterest",
    name: "最大利息",
    desc: "最大利息提升至7金币。",
    logo: "https://game.gtimg.cn/images/lol/act/img/tft/RegionPortal/TFT_Portals_Gold_MaxInterest.png",
    video: "",
    bgImage: "",
    country: "最大利息",
    versionId: "133",
    seasonId: "45",
    creater: "v_qjmqu",
    createTime: "2024-03-11 10:48:27",
    updater: "",
    updateTime: "",
    isDelete: "0",
  },
  {
    id: "TFT_Portals_Headliner_Entourage",
    name: "明星风采",
    desc: "在战斗开始时，【赛季之星】们会提供150生命值和15%攻击速度给邻格的友方弈子们。",
    logo: "https://game.gtimg.cn/images/lol/act/img/tft/RegionPortal/TFT_Portals_Headliner_Entourage.png",
    video: "",
    bgImage: "",
    country: "明星风采",
    versionId: "133",
    seasonId: "45",
    creater: "v_qjmqu",
    createTime: "2024-03-11 10:48:27",
    updater: "",
    updateTime: "",
    isDelete: "0",
  },
  {
    id: "TFT_Portals_Items_RadiantItem",
    name: "光明武器",
    desc: "在游戏后期从5件光明武器(各个成装的超级加强版)中选出1件。",
    logo: "https://game.gtimg.cn/images/lol/act/img/tft/RegionPortal/TFT_Portals_Items_RadiantItem.png",
    video: "",
    bgImage: "",
    country: "光明武器",
    versionId: "133",
    seasonId: "45",
    creater: "v_qjmqu",
    createTime: "2024-03-11 10:48:27",
    updater: "",
    updateTime: "",
    isDelete: "0",
  },
  {
    id: "TFT_Portals_Items_Spatula",
    name: "金铲铲",
    desc: "开局拥有1个【金铲铲】。",
    logo: "https://game.gtimg.cn/images/lol/act/img/tft/RegionPortal/TFT_Portals_Items_Spatula.png",
    video: "",
    bgImage: "",
    country: "金铲铲",
    versionId: "133",
    seasonId: "45",
    creater: "v_qjmqu",
    createTime: "2024-03-11 10:48:27",
    updater: "",
    updateTime: "",
    isDelete: "0",
  },
  {
    id: "TFT_Portals_Items_SupportAnvil",
    name: "辅助装锻造器",
    desc: "在游戏开始时获得1个【辅助装锻造器】。辅助装可提供光环来增强你的队伍。",
    logo: "https://game.gtimg.cn/images/lol/act/img/tft/RegionPortal/TFT_Portals_Items_SupportAnvil.png",
    video: "",
    bgImage: "",
    country: "辅助装锻造器",
    versionId: "133",
    seasonId: "45",
    creater: "v_qjmqu",
    createTime: "2024-03-11 10:48:27",
    updater: "",
    updateTime: "",
    isDelete: "0",
  },
  {
    id: "TFT_Portals_Items_TomeOfTraits",
    name: "纹章之书",
    desc: "在游戏开始时获得1本【纹章之书】，它能让你从4个纹章中选出1个。",
    logo: "https://game.gtimg.cn/images/lol/act/img/tft/RegionPortal/TFT_Portals_Items_TomeOfTraits.png",
    video: "",
    bgImage: "",
    country: "纹章之书",
    versionId: "133",
    seasonId: "45",
    creater: "v_qjmqu",
    createTime: "2024-03-11 10:48:27",
    updater: "",
    updateTime: "",
    isDelete: "0",
  },
  {
    id: "TFT_Portals_Unique_MaxHealthDecrease",
    name: "玩家生命值降低",
    desc: "开局拥有85玩家生命值。",
    logo: "https://game.gtimg.cn/images/lol/act/img/tft/RegionPortal/TFT_Portals_Unique_MaxHealthDecrease.png",
    video: "",
    bgImage: "",
    country: "玩家生命值降低",
    versionId: "133",
    seasonId: "45",
    creater: "v_qjmqu",
    createTime: "2024-03-11 10:48:27",
    updater: "",
    updateTime: "",
    isDelete: "0",
  },
];
