export default [
  {
    id: "1",
    title: "亚托克斯",
    desc: "【亚托克斯】为你提供1个【基础装备锻造器】、玩家生命值或金币。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10063.jpg",
    videoUrl: "",
    imageUrl: "Aatrox_HealthXPChoice",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:10",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "2",
    title: "阿狸",
    desc: "【阿狸】的吻可为玩家提供生命值。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10064.jpg",
    videoUrl: "",
    imageUrl: "Ahri_BestowHealth",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:10",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "3",
    title: "阿狸",
    desc: "【阿狸】赐予你的队伍一个战斗祝福，持续到本局游戏结束。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10064.jpg",
    videoUrl: "",
    imageUrl: "Ahri_TeamBuffChoice",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:10",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "4",
    title: "拉露恩",
    desc: "【拉露恩】为你提供1个成装锻造器。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10065.jpg",
    videoUrl: "",
    imageUrl: "Alune_CompletedAnvilFirstEncounter",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:10",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "5",
    title: "拉露恩",
    desc: "【拉露恩】提供成装，让你选择一件。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10065.jpg",
    videoUrl: "",
    imageUrl: "Alune_CompletedArmory",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:10",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "6",
    title: "拉露恩",
    desc: "【拉露恩】为选秀回合的每个弈子添加1件成装。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10065.jpg",
    videoUrl: "",
    imageUrl: "Alune_CompletedCarousel",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:10",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "7",
    title: "拉露恩",
    desc: "【拉露恩】永久强化你某个费用的弈子们。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10065.jpg",
    videoUrl: "",
    imageUrl: "Alune_UnitPowerChoice",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:10",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "8",
    title: "阿木木",
    desc: "本次的选秀回合中，全都是【阿木木】的2星3费朋友！",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10066.jpg",
    videoUrl: "",
    imageUrl: "Amumu_ThreeCostTwoStarCarousel",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:10",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "9",
    title: "阿木木",
    desc: "【阿木木】会为所有愿意和他交朋友的人送上超棒的礼物。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10066.jpg",
    videoUrl: "",
    imageUrl: "Amumu_FonTot",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:10",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "10",
    title: "安妮",
    desc: "接下来几个回合中，【安妮】会为你提供更好的商店供应或更多金币。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10067.jpg",
    videoUrl: "",
    imageUrl: "Annie_HighEndShoppingOrInterestChoice",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:10",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "11",
    title: "厄斐琉斯",
    desc: "【厄斐琉斯】为你召唤2个【基础装备锻造器】。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10068.jpg",
    videoUrl: "",
    imageUrl: "Aphelios_TwoComponentAnvils",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:10",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "12",
    title: "艾希",
    desc: "接下来3场玩家对战中，【艾希】将揭示你的下一个对手。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10069.jpg",
    videoUrl: "",
    imageUrl: "Ashe_FutureSight",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:10",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "13",
    title: "艾希",
    desc: "【艾希】为你揭示即将遇到的对手，直到本局游戏结束。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10069.jpg",
    videoUrl: "",
    imageUrl: "Ashe_FutureSight",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:10",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "14",
    title: "阿兹尔",
    desc: "【阿兹尔】提供6次免费刷新，可保留至使用为止。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10070.jpg",
    videoUrl: "",
    imageUrl: "Azir_Rerolls",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:10",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "15",
    title: "阿兹尔",
    desc: "【阿兹尔】将3-2和4-2的强化符文移至随机回合。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10070.jpg",
    videoUrl: "",
    imageUrl: "Azir_ShiftAugmentRounds",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:10",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "16",
    title: "巴德",
    desc: "【巴德】将每个玩家升级至3级！",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10071.jpg",
    videoUrl: "",
    imageUrl: "Bard_Level3Start",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:10",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "17",
    title: "巴德",
    desc: "【巴德】在本局游戏中为你提供以3级开局的选项。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10071.jpg",
    videoUrl: "",
    imageUrl: "Bard_Level3Start",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:10",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "18",
    title: "凯特琳",
    desc: "【凯特琳】在本回合为你提供4次免费刷新。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10072.jpg",
    videoUrl: "",
    imageUrl: "Caitlyn_RerollsThisRound",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:10",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "19",
    title: "科加斯",
    desc: "【科加斯】为你提供2个【次级英雄复制器】或1个【英雄复制器】。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10073.jpg",
    videoUrl: "",
    imageUrl: "ChoGath_LesserNormalDupe",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:10",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "20",
    title: "科加斯",
    desc: "如果你能满足【科加斯】的饥饿感，他便会给你一份馈赠……",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10073.jpg",
    videoUrl: "",
    imageUrl: "ChoGath_TradeShopSlotForComponents",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "21",
    title: "德莱厄斯",
    desc: "敌方弈子被击杀时有30%几率掉落战利品。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10074.jpg",
    videoUrl: "",
    imageUrl: "Darius_SpoilsOfWar",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "22",
    title: "德莱厄斯",
    desc: "【德莱厄斯】让你在20经验值和10次免费刷新之间做出选择。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10074.jpg",
    videoUrl: "",
    imageUrl: "Darius_XPReroll",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "23",
    title: "德莱厄斯",
    desc: "【德莱厄斯】将高亮备战席栏位中的弈子转换为随机的同费弈子，持续5个回合。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10074.jpg",
    videoUrl: "",
    imageUrl: "Darius_PandorasBench",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "24",
    title: "黛安娜",
    desc: "本回合中，你出售某个弈子时，【黛安娜】会将其成装劈砍成基础装备。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10075.jpg",
    videoUrl: "",
    imageUrl: "Diana_SalvageBin",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "25",
    title: "黛安娜",
    desc: "你出售某弈子时，【黛安娜】会将其成装劈砍成基础装备。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10075.jpg",
    videoUrl: "",
    imageUrl: "Diana_SalvageBin",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "26",
    title: "黛安娜",
    desc: "【黛安娜】为你提供一个最多可刷新3次的【秘宝武器库】。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10075.jpg",
    videoUrl: "",
    imageUrl: "Diana_TreasureArmory",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "27",
    title: "可酷伯",
    desc: "【可酷伯】邀请你与他共舞！加入的玩家越多，奖励就越棒！",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10076.jpg",
    videoUrl: "",
    imageUrl: "FortuneYordle_DanceWithMe",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "28",
    title: "加里奥",
    desc: "【加里奥】为选秀回合的每个弈子添加1件防御型基础装备。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10077.jpg",
    videoUrl: "",
    imageUrl: "Galio_DoubleComponentCarousel",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "29",
    title: "盖伦",
    desc: "接下来3个回合，购买的所有弈子都会永久获得100生命值。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10078.jpg",
    videoUrl: "",
    imageUrl: "Garen_PermanentHPOnPurchase",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "30",
    title: "纳尔",
    desc: "【纳尔】让你的下一个强化符文选项可以额外刷新1次。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10079.jpg",
    videoUrl: "",
    imageUrl: "Gnar_BonusRerollNextAugment",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "31",
    title: "纳尔",
    desc: "【纳尔】用2星2费弈子填满选秀回合。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10079.jpg",
    videoUrl: "",
    imageUrl: "Gnar_TwoCostTwoStarCarousel",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "32",
    title: "彗",
    desc: "在接下来的5个回合中，【彗】画出一个假人。每当它在玩家对战回合中幸存下来时，获得1金币。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10080.jpg",
    videoUrl: "",
    imageUrl: "Hwei_DummyEscort",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "33",
    title: "彗",
    desc: "【彗】绘出全是5费弈子的选秀回合。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10080.jpg",
    videoUrl: "",
    imageUrl: "Hwei_FiveCostCarousel",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "34",
    title: "彗",
    desc: "【彗】使你的第一个商店栏位提供量身定制的弈子，直至对局结束。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10080.jpg",
    videoUrl: "",
    imageUrl: "Hwei_TailoredShopSlot",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "35",
    title: "俄洛伊",
    desc: "【俄洛伊】在本回合为你提供8次免费刷新。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10081.jpg",
    videoUrl: "",
    imageUrl: "Illaoi_RerollsThisRound",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "36",
    title: "俄洛伊",
    desc: "【俄洛伊】将3-2的强化符文移至随机回合。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10081.jpg",
    videoUrl: "",
    imageUrl: "Illaoi_ShiftAugmentRounds",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "37",
    title: "艾瑞莉娅",
    desc: "【艾瑞莉娅】解除所有玩家的限制，使其可以在此选秀回合中自由移动。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10082.jpg",
    videoUrl: "",
    imageUrl: "Irelia_FreeCarousel",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "38",
    title: "艾瑞莉娅",
    desc: "【艾瑞莉娅】让你接下来的6次商店刷新包含每个费用各1个弈子。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10082.jpg",
    videoUrl: "",
    imageUrl: "Irelia_OneOfEachCost",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "39",
    title: "迦娜",
    desc: "【迦娜】为你提供一个最多可刷新10次的【秘宝武器库】。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10083.jpg",
    videoUrl: "",
    imageUrl: "Janna_TreasureArmory",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "40",
    title: "迦娜",
    desc: "【迦娜】让你在不同的弈子之间做出选择。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10083.jpg",
    videoUrl: "",
    imageUrl: "Janna_UnitChoice",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "41",
    title: "迦娜",
    desc: "【迦娜】为你提供2个在3回合后消失的【灵风】。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10083.jpg",
    videoUrl: "",
    imageUrl: "Janna_ZephyrTime",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "42",
    title: "贾克斯",
    desc: "【贾克斯】让你在刷新次数和弈子之间做出选择。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10084.jpg",
    videoUrl: "",
    imageUrl: "Jax_GoldRerollChoice",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "43",
    title: "贾克斯",
    desc: "【贾克斯】从不同的武器库中为你提供1件武器。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10084.jpg",
    videoUrl: "",
    imageUrl: "Jax_SupportArtifactChoice",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "44",
    title: "卡莎",
    desc: "【卡莎】为你提供一个可无限次使用的【装备拆卸器】，或金币。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10085.jpg",
    videoUrl: "",
    imageUrl: "Kaisa_GoldenRemoverChoice",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "45",
    title: "凯隐",
    desc: "本局游戏到此结束。你目前所处的位置就是你的最终排名。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10087.jpg",
    videoUrl: "",
    imageUrl: "Kayn_PlayerDeathFinish",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "46",
    title: "凯隐",
    desc: "本局游戏会在5-4时结束。届时，你所处的位置将成为你的最终排名。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10087.jpg",
    videoUrl: "",
    imageUrl: "Kayn_PlayerDeathStart",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "47",
    title: "凯隐",
    desc: "【凯隐】为你提供【死亡之刃】和【死亡之帽】。这些装备将持续3个回合。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10087.jpg",
    videoUrl: "",
    imageUrl: "Kayn_DeathItems",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "48",
    title: "卡兹克",
    desc: "【卡兹克】立即为你提供下一个强化符文。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10088.jpg",
    videoUrl: "",
    imageUrl: "KhaZix_GainNextAugment",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "49",
    title: "卡兹克",
    desc: "接下来3个回合中，【卡兹克】使经验值价格从4金币减为3金币。进化。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10088.jpg",
    videoUrl: "",
    imageUrl: "KhaZix_XPCosts3",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "50",
    title: "卡兹克",
    desc: "本局游戏中，【卡兹克】使经验值价格从4金币减为3金币。进化！",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10088.jpg",
    videoUrl: "",
    imageUrl: "KhaZix_XPCosts3",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "51",
    title: "千珏",
    desc: "【千珏】规定本局游戏仅能存在偶数等级。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10089.jpg",
    videoUrl: "",
    imageUrl: "Kindred_EvenLevels",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "52",
    title: "千珏",
    desc: "【千珏】为你提供一件持续3个回合的临时装备。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10089.jpg",
    videoUrl: "",
    imageUrl: "Kindred_LifeDeathItemChoice",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "53",
    title: "千珏",
    desc: "【千珏】为你提供一个选择：红或蓝。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10089.jpg",
    videoUrl: "",
    imageUrl: "Kindred_RedBlueChoice",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "54",
    title: "千珏",
    desc: "【千珏】为你提供3个持续3个回合的【训练假人】。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10089.jpg",
    videoUrl: "",
    imageUrl: "Kindred_TrainingDummies",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "55",
    title: "克格莫",
    desc: "【克格莫】将2-1的强化符文移至随机回合。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10090.jpg",
    videoUrl: "",
    imageUrl: "KogMaw_ShiftAugmentRounds",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "56",
    title: "李青",
    desc: "【李青】为你提供一个最多可刷新10次的【秘宝武器库】。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10091.jpg",
    videoUrl: "",
    imageUrl: "LeeSin_TreasureArmory",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "57",
    title: "莉莉娅",
    desc: "【莉莉娅】将所有强化符文移至随机回合！",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10092.jpg",
    videoUrl: "",
    imageUrl: "Lillia_ShiftAugmentRounds",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "58",
    title: "丽桑卓",
    desc: "【丽桑卓】为你提供各种装备供你购买……但价钱昂贵。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10093.jpg",
    videoUrl: "",
    imageUrl: "Lissandra_SpendGold",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "59",
    title: "丽桑卓",
    desc: "【丽桑卓】提供光明武器，让你选择一件。所选的装备将在3回合后消失。获得1个【装备拆卸器】。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10093.jpg",
    videoUrl: "",
    imageUrl: "Lissandra_TempRadiantItem",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "60",
    title: "丽桑卓",
    desc: "【丽桑卓】愿意向你出售任意数量的基础装备。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10093.jpg",
    videoUrl: "",
    imageUrl: "Lissandra_TradeGoldForItemChoice",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "61",
    title: "拉克丝",
    desc: "【拉克丝】将4-2的强化符文移至随机回合。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10094.jpg",
    videoUrl: "",
    imageUrl: "Lux_ShiftAugmentRounds",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "62",
    title: "拉克丝",
    desc: "【拉克丝】为你提供2件随机的辅助装。这些装备将在3回合后消失。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10094.jpg",
    videoUrl: "",
    imageUrl: "Lux_TempSupportItems",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "63",
    title: "墨菲特",
    desc: "本回合：每当你将一个弈子移到备战席时，【墨菲特】就会把该弈子的装备震掉。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10095.jpg",
    videoUrl: "",
    imageUrl: "Malphite_BenchPopOff",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "64",
    title: "墨菲特",
    desc: "每当你将一个弈子移到备战席时，【墨菲特】就会把该弈子的装备震掉。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10095.jpg",
    videoUrl: "",
    imageUrl: "Malphite_BenchPopOff",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "65",
    title: "莫甘娜",
    desc: "【莫甘娜】用4费弈子填满选秀回合。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10096.jpg",
    videoUrl: "",
    imageUrl: "Morgana_FourCostCarousel",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "66",
    title: "莫甘娜",
    desc: "【莫甘娜】为你提供一个选择。升级你的下一个2费弈子，或获得金币。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10096.jpg",
    videoUrl: "",
    imageUrl: "Morgana_GoldOrUpgrade",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "67",
    title: "诺提勒斯",
    desc: "【诺提勒斯】为你提供：在击杀敌人或友军阵亡时掉落金币。持续3个回合。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10097.jpg",
    videoUrl: "",
    imageUrl: "Nautilus_KillDeathGold",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "68",
    title: "妮蔻",
    desc: "【妮蔻】召唤1个随机的3星1费生灵，在3场玩家对战中提供帮助。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10098.jpg",
    videoUrl: "",
    imageUrl: "Neeko_1CostSpirit",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "69",
    title: "妮蔻",
    desc: "【妮蔻】召唤1个随机的5费灵魂，在3场玩家对战中提供帮助。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10098.jpg",
    videoUrl: "",
    imageUrl: "Neeko_5CostSpirit",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "70",
    title: "妮蔻",
    desc: "【妮蔻】为选秀回合的每个弈子添加1个【英雄复制器】！",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10098.jpg",
    videoUrl: "",
    imageUrl: "Neeko_DuplicatorCarousel",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "71",
    title: "妮蔻",
    desc: "【妮蔻】为选秀回合的每个弈子添加1个【次级英雄复制器】！",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10098.jpg",
    videoUrl: "",
    imageUrl: "Neeko_LesserDuplicatorCarousel",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "72",
    title: "奥恩",
    desc: "【奥恩】勉为其难地为你提供1个【神器锻造器】。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10099.jpg",
    videoUrl: "",
    imageUrl: "Ornn_ArtifactAnvilFirstEncounter",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "73",
    title: "奥恩",
    desc: "【奥恩】提供神器，让你选择一件。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10099.jpg",
    videoUrl: "",
    imageUrl: "Ornn_ArtifactArmory",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "74",
    title: "奥恩",
    desc: "奥恩锻造6件持续1回合的神器。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10099.jpg",
    videoUrl: "",
    imageUrl: "Ornn_ArtifactBlitz",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "75",
    title: "奥恩",
    desc: "【奥恩】为选秀回合的每个弈子添加1件神器。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10099.jpg",
    videoUrl: "",
    imageUrl: "Ornn_ArtifactCarousel",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "76",
    title: "奇亚娜",
    desc: "【奇亚娜】提供光明武器，让你选择一件。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10100.jpg",
    videoUrl: "",
    imageUrl: "Qiyana_RadiantArmory",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "77",
    title: "奇亚娜",
    desc: "【奇亚娜】规定选秀回合的每个弈子都拥有1件光明武器。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10100.jpg",
    videoUrl: "",
    imageUrl: "Qiyana_RadiantCarousel",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "78",
    title: "锐雯",
    desc: "【锐雯】为选秀回合的每个弈子添加1件基础装备。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10103.jpg",
    videoUrl: "",
    imageUrl: "Riven_ComponentCarousel",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "79",
    title: "赛娜",
    desc: "【赛娜】可以帮你设置连胜或连败。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10104.jpg",
    videoUrl: "",
    imageUrl: "Senna_StreakChoice",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "80",
    title: "瑟提",
    desc: "与【瑟提】一起锻炼，让自己变得更大。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10105.jpg",
    videoUrl: "",
    imageUrl: "Sett_SettSquatIncrease",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "81",
    title: "瑟提",
    desc: "接下来3个回合里，【瑟提】会借给你一些【训练假人】。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10105.jpg",
    videoUrl: "",
    imageUrl: "Sett_TrainingDummies",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "82",
    title: "慎",
    desc: "【慎】为你提供一次初始包的选择机会，这些初始包内含若干弈子和1件基础装备。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10106.jpg",
    videoUrl: "",
    imageUrl: "Shen_StarterPackEarly",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "83",
    title: "慎",
    desc: "【慎】看守着选秀回合，其中所有弈子都携带一件辅助装。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10106.jpg",
    videoUrl: "",
    imageUrl: "Shen_SupportCarousel",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "84",
    title: "希维尔",
    desc: "【希维尔】的战斗口号使你变得更加迅捷。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10107.jpg",
    videoUrl: "",
    imageUrl: "Sivir_SpeedIncrease",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "85",
    title: "索拉卡",
    desc: "【索拉卡】送给你1个【辅助装锻造器】。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10108.jpg",
    videoUrl: "",
    imageUrl: "Soraka_SupportAnvilFirstEncounter",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "86",
    title: "索拉卡",
    desc: "【索拉卡】提供辅助装，让你选择一件。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10108.jpg",
    videoUrl: "",
    imageUrl: "Soraka_SupportArmory",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "87",
    title: "索拉卡",
    desc: "【索拉卡】为选秀回合的每个弈子添加1件辅助装。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10108.jpg",
    videoUrl: "",
    imageUrl: "Soraka_SupportCarousel",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "88",
    title: "辛德拉",
    desc: "【辛德拉】使你棋盘上所有未激活的羁绊都以其最低等级激活。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10110.jpg",
    videoUrl: "",
    imageUrl: "Syndra_AllTraitsActive",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "89",
    title: "辛德拉",
    desc: "【辛德拉】释放出一个由2星4费弈子组成的选秀回合。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10110.jpg",
    videoUrl: "",
    imageUrl: "Syndra_FourCostTwoStarCarousel",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "90",
    title: "辛德拉",
    desc: "【辛德拉】将2-1和4-2的强化符文移至随机回合。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10110.jpg",
    videoUrl: "",
    imageUrl: "Syndra_ShiftAugmentRounds",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "91",
    title: "塔姆",
    desc: "站在水坑里为【塔姆】抓鱼。他吃的鱼越多，大家获得的战利品就越多！",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10111.jpg",
    videoUrl: "",
    imageUrl: "TahmKench_FeedTheFrog",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "92",
    title: "塔姆",
    desc: "【塔姆】为你提供1件【基础装备锻造器】或10金币。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10111.jpg",
    videoUrl: "",
    imageUrl: "TahmKench_GoldOrComponent",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "93",
    title: "提莫",
    desc: "【提莫】让你可以在本局游戏中额外刷新所有强化符文1次！",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10112.jpg",
    videoUrl: "",
    imageUrl: "Teemo_BonusAugmentRerollsThisGame",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "94",
    title: "提莫",
    desc: "【提莫】为选秀回合的每个弈子添加1个【金铲铲】！",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10112.jpg",
    videoUrl: "",
    imageUrl: "Teemo_SpatulaCarousel",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "95",
    title: "提莫",
    desc: "猜测你下一场对战的结果。如果猜对了，【提莫】将送上一份奖励！",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10112.jpg",
    videoUrl: "",
    imageUrl: "Teemo_WinOrLoseChoice",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "96",
    title: "锤石",
    desc: "【锤石】释放出一个选秀回合，其中所有弈子都携带神器。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10113.jpg",
    videoUrl: "",
    imageUrl: "Thresh_ArtifactCarousel",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "97",
    title: "锤石",
    desc: "【锤石】将2-1和3-2的强化符文移至随机回合。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10113.jpg",
    videoUrl: "",
    imageUrl: "Thresh_ShiftAugmentRounds",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "98",
    title: "崔丝塔娜",
    desc: "【崔丝塔娜】提供一份金币礼物！",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10115.jpg",
    videoUrl: "",
    imageUrl: "Tristana_GiveGold",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "99",
    title: "乌迪尔",
    desc: "【乌迪尔】根据所选的兽灵为你提供2件基础装备。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10116.jpg",
    videoUrl: "",
    imageUrl: "Udyr_ComponentChoice",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "100",
    title: "乌迪尔",
    desc: "【乌迪尔】提供4次免费刷新，可保留至使用为止。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10116.jpg",
    videoUrl: "",
    imageUrl: "Udyr_Rerolls",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "101",
    title: "乌迪尔",
    desc: "【乌迪尔】为你提供一件辅助装，此装备持续3个回合。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10116.jpg",
    videoUrl: "",
    imageUrl: "Udyr_SupportChoice",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "102",
    title: "沃利贝尔",
    desc: "【沃利贝尔】用3费弈子填满选秀回合。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10117.jpg",
    videoUrl: "",
    imageUrl: "Volibear_ThreeCostCarousel",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "103",
    title: "孙悟空",
    desc: "【孙悟空】激活【天选之子】：可为羁绊提供+1人数的2星单位。出售你的【天选之子】以购买一个新的【天选之子】。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10118.jpg",
    videoUrl: "",
    imageUrl: "Wukong_ActivateChosenTwoStar",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "104",
    title: "孙悟空",
    desc: "【孙悟空】为你提供6件持续1回合的光明武器。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10118.jpg",
    videoUrl: "",
    imageUrl: "Wukong_RadiantBlitz",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "105",
    title: "孙悟空",
    desc: "【孙悟空】为这个选秀回合的每个弈子添加1件光明武器。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10118.jpg",
    videoUrl: "",
    imageUrl: "Wukong_RadiantCarousel",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "106",
    title: "霞洛",
    desc: "【洛】鼓励你变形重组你的棋盘——或者【霞】为你提供一些金币。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10120.jpg",
    videoUrl: "",
    imageUrl: "XayahRakan_RecombobulateChoice",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "107",
    title: "亚索",
    desc: "接下来4场玩家对战中，【亚索】为开局时处于后3排的单位提供200临时生命值。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10121.jpg",
    videoUrl: "",
    imageUrl: "Yasuo_BackRowHealth",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "108",
    title: "永恩",
    desc: "【永恩】让你的下一个强化符文选项可以额外刷新2次。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10122.jpg",
    videoUrl: "",
    imageUrl: "Yone_BonusRerollNextAugment",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "109",
    title: "永恩",
    desc: "【永恩】为选秀回合的每个英雄额外添加1件攻击型基础装备。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10122.jpg",
    videoUrl: "",
    imageUrl: "Yone_DoubleComponentCarousel",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "110",
    title: "约里克",
    desc: "无论等级高低，【约里克】都能让你随时部署至少7个弈子。获得10金币。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10123.jpg",
    videoUrl: "",
    imageUrl: "Yorick_MinimumSevenUnits",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "111",
    title: "约里克",
    desc: "接下来3个回合中，【约里克】将你商店的刷新费用减1。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10123.jpg",
    videoUrl: "",
    imageUrl: "Yorick_RerollsCost1",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "112",
    title: "约里克",
    desc: "【约里克】将你商店的刷新费用减1。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10123.jpg",
    videoUrl: "",
    imageUrl: "Yorick_RerollsCost1",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "113",
    title: "佐伊",
    desc: "【佐伊】改变现实，让本局游戏仅存在奇数等级。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10124.jpg",
    videoUrl: "",
    imageUrl: "Zoe_OddLevels",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "114",
    title: "佐伊",
    desc: "【佐伊】为你提供2个【诡术师之镜】。它们将在3回合内消失。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10124.jpg",
    videoUrl: "",
    imageUrl: "Zoe_TrickstersGlass",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
  {
    id: "115",
    title: "婕拉",
    desc: "选择1件基础装备。【婕拉】为你提供3件该基础装备。",
    notes: "",
    logoUrl:
      "https://game.gtimg.cn/images/lol/act/img/tft/encounters/10125.jpg",
    videoUrl: "",
    imageUrl: "Zyra_TripleComponent",
    versionId: "132",
    seasonId: "47",
    creater: "eddli",
    createTime: "2024-03-14 17:54:11",
    updater: "eddli",
    updateTime: "2024-03-14 18:05:32",
    isDelete: "0",
  },
];
